package rules;

import com.chen.drools.bean.Person
import com.chen.drools.bean.School

rule "testContains"
    when
        $s:School()
        $p:Person($s.classNameList contains className)
    then
        System.out.println("testContains");
end

rule "testMemberOf"
    when
        $s:School()
        $p:Person(className memberOf $s.classNameList)
    then
        System.out.println("testMemberOf");
end

rule "testMatches"
    when
        $p:Person(className matches "一.*")
    then
        System.out.println("testMatches");
end

rule "testSoundslike"
    when
        $p:Person(name soundslike "LefChen")
    then
        System.out.println("testSoundslike");
end

rule "testStr"
    when
        $p:Person(className str[endsWith] "班")
    then
        System.out.println("testStr");
end
