package rules.hello

import com.chen.drools.bean.Person

rule "test001"
    when
        eval(false)
    then
        System.out.println("hello drools");
end

rule "test002"
    when
        $p:Person(age==18)
    then
        System.out.println("匹配年龄为18的人:" + $p);
        $p.setAge(20);
        update($p);
end

rule "test003"
    when
        $p:Person(age==20)
    then
        System.out.println("匹配年龄为20的人:" + $p);
end
